import type { Metadata } from "next";
import { Playfair_Display, Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BooksProvider from "@/contexts/BooksContext";

const playfairDisplay = Playfair_Display({
	variable: "--font-playfair",
	subsets: ["latin"],
});

const workSans = Work_Sans({
	variable: "--font-work",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Book Vibe",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			data-theme="light"
			className={`${playfairDisplay.variable} ${workSans.variable} h-full antialiased`}>
			<body className="min-h-full max-w-7xl mx-auto flex flex-col">
				<BooksProvider>
					<Navbar />

					<main>{children}</main>
				</BooksProvider>
			</body>
		</html>
	);
}
